apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontendagent
  annotations:
    run.googleapis.com/ingress: all
  labels:
    cloud.googleapis.com/location: southamerica-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: southamerica-west1-docker.pkg.dev/agentappointment/repobackendagent/frontendagent:IMAGE_TAG
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
  traffic:
    - percent: 100
      latestRevision: true
